#!/bin/bash

LASTDATE=$(tail -2 updateDates.txt | head -1)
TODAY=$(date +%Y%m%d)
source db.conf


if [ "$INDEX" == "ec2" ]; then
psql -c "alter table public.voterfile_new add CONSTRAINT voterfile_pk_$TODAY PRIMARY KEY (sos_voterid);"
psql -c "create index first_name_idx_$TODAY on public.voterfile_new using btree (first_name);"
psql -c "create index last_name_idx_$TODAY  on public.voterfile_new using btree (last_name);"
psql -c "CREATE INDEX voterfile_county_number_$TODAY  ON public.voterfile_new USING btree (county_number) ;"
psql -c "CREATE INDEX voterfile_date_of_birth_$TODAY  ON public.voterfile_new USING btree (date_of_birth) ;"
psql -c "CREATE INDEX voterfile_age_$TODAY  ON public.voterfile_new USING btree (date_part('year', age(date_of_birth))) ;"
psql -c "CREATE INDEX voterfile_voter_status_$TODAY  ON public.voterfile_new USING btree (voter_status) ;"
psql -c "grant select on table public.voterfile_new to ohiovotes;"
else
	psql -c "alter table public.voterfile_new add CONSTRAINT voterfile_pk_$TODAY  PRIMARY KEY (sos_voterid);"
	psql -c "create index first_name_idx_$TODAY  on public.voterfile_new using btree (first_name);"
	psql -c "create index last_name_idx_$TODAY  on public.voterfile_new using btree (last_name);"
	psql -c "create index name_trgm_idx_$TODAY  on public.voterfile_new using GIST ((coalesce(first_name, '') || ' ' || coalesce(last_name, '')) gist_trgm_ops);"
	psql -c "CREATE INDEX first_trgm_idx_$TODAY  ON public.voterfile_new USING gin (first_name gin_trgm_ops) ;"
	psql -c "CREATE INDEX first_name_metaphone_idx_$TODAY  ON public.voterfile_new USING gin (metaphone(first_name, 3) gin_trgm_ops) ;"
	psql -c "CREATE INDEX last_name_metaphone_idx_$TODAY  ON public.voterfile_new USING gin (metaphone(last_name, 5) gin_trgm_ops) ;"
	psql -c "CREATE INDEX last_trgm_idx_$TODAY  ON public.voterfile_new USING gin (last_name gin_trgm_ops) ;"
	psql -c "CREATE INDEX voterfile_career_center_$TODAY  ON public.voterfile_new USING btree (career_center) ;"
	psql -c "CREATE INDEX voterfile_city_$TODAY  ON public.voterfile_new USING gin (city gin_trgm_ops) ;"
	psql -c "CREATE INDEX voterfile_city_school_district_$TODAY  ON public.voterfile_new USING btree (city_school_district) ;"
	psql -c "CREATE INDEX voterfile_congressional_district_$TODAY  ON public.voterfile_new USING btree (congressional_district) ;"
	psql -c "CREATE INDEX voterfile_county_court_district_$TODAY  ON public.voterfile_new USING btree (county_court_district) ;"
	psql -c "CREATE INDEX voterfile_county_id_$TODAY  ON public.voterfile_new USING btree (county_id) ;"
	psql -c "CREATE INDEX voterfile_county_number_$TODAY  ON public.voterfile_new USING btree (county_number) ;"
	psql -c "CREATE INDEX voterfile_court_of_appeals_$TODAY  ON public.voterfile_new USING btree (court_of_appeals) ;"
	psql -c "CREATE INDEX voterfile_date_of_birth_$TODAY  ON public.voterfile_new USING btree (date_of_birth) ;"
	psql -c "CREATE INDEX voterfile_age_$TODAY  ON public.voterfile_new USING btree (date_part('year', age(date_of_birth))) ;"
	psql -c "CREATE INDEX voterfile_edu_service_center_district_$TODAY  ON public.voterfile_new USING btree (edu_service_center_district) ;"
	psql -c "CREATE INDEX voterfile_exempted_vill_school_district_$TODAY  ON public.voterfile_new USING btree (exempted_vill_school_district) ;"
	psql -c "CREATE INDEX voterfile_first_name_$TODAY  ON public.voterfile_new USING gin (first_name) ;"
	psql -c "CREATE INDEX voterfile_general_06_07_2016_$TODAY  ON public.voterfile_new USING btree (general_06_07_2016) ;"
	psql -c "CREATE INDEX voterfile_general_11_02_2004_$TODAY  ON public.voterfile_new USING btree (general_11_02_2004) ;"
	psql -c "CREATE INDEX voterfile_general_11_02_2010_$TODAY  ON public.voterfile_new USING btree (general_11_02_2010) ;"
	psql -c "CREATE INDEX voterfile_general_11_03_2009_$TODAY  ON public.voterfile_new USING btree (general_11_03_2009) ;"
	psql -c "CREATE INDEX voterfile_general_11_03_2015_$TODAY  ON public.voterfile_new USING btree (general_11_03_2015) ;"
	psql -c "CREATE INDEX voterfile_general_11_04_2003_$TODAY  ON public.voterfile_new USING btree (general_11_04_2003) ;"
	psql -c "CREATE INDEX voterfile_general_11_04_2008_$TODAY  ON public.voterfile_new USING btree (general_11_04_2008) ;"
	psql -c "CREATE INDEX voterfile_general_11_04_2014_$TODAY  ON public.voterfile_new USING btree (general_11_04_2014) ;"
	psql -c "CREATE INDEX voterfile_general_11_05_2002_$TODAY  ON public.voterfile_new USING btree (general_11_05_2002) ;"
	psql -c "CREATE INDEX voterfile_general_11_05_2013_$TODAY  ON public.voterfile_new USING btree (general_11_05_2013) ;"
	psql -c "CREATE INDEX voterfile_general_11_06_2001_$TODAY  ON public.voterfile_new USING btree (general_11_06_2001) ;"
	psql -c "CREATE INDEX voterfile_general_11_06_2007_$TODAY  ON public.voterfile_new USING btree (general_11_06_2007) ;"
	psql -c "CREATE INDEX voterfile_general_11_06_2012_$TODAY  ON public.voterfile_new USING btree (general_11_06_2012) ;"
	psql -c "CREATE INDEX voterfile_general_11_07_2000_$TODAY  ON public.voterfile_new USING btree (general_11_07_2000) ;"
	psql -c "CREATE INDEX voterfile_general_11_07_2006_$TODAY  ON public.voterfile_new USING btree (general_11_07_2006) ;"
	psql -c "CREATE INDEX voterfile_general_11_07_2017_$TODAY  ON public.voterfile_new USING btree (general_11_07_2017) ;"
	psql -c "CREATE INDEX voterfile_general_11_08_2005_$TODAY  ON public.voterfile_new USING btree (general_11_08_2005) ;"
	psql -c "CREATE INDEX voterfile_general_11_08_2011_$TODAY  ON public.voterfile_new USING btree (general_11_08_2011) ;"
	psql -c "CREATE INDEX voterfile_general_11_08_2016_$TODAY  ON public.voterfile_new USING btree (general_11_08_2016) ;"
	psql -c "CREATE INDEX voterfile_general_11_18_2008_$TODAY  ON public.voterfile_new USING btree (general_11_18_2008) ;"
	psql -c "CREATE INDEX voterfile_general_12_11_2007_$TODAY  ON public.voterfile_new USING btree (general_12_11_2007) ;"
	psql -c "CREATE INDEX voterfile_last_name_$TODAY  ON public.voterfile_new USING gin (last_name) ;"
	psql -c "CREATE INDEX voterfile_library_$TODAY  ON public.voterfile_new USING btree (library) ;"
	psql -c "CREATE INDEX voterfile_local_school_district_$TODAY  ON public.voterfile_new USING btree (local_school_district) ;"
	psql -c "CREATE INDEX voterfile_mailing_address1_$TODAY  ON public.voterfile_new USING btree (mailing_address1) ;"
	psql -c "CREATE INDEX voterfile_mailing_city_$TODAY  ON public.voterfile_new USING btree (mailing_city) ;"
	psql -c "CREATE INDEX voterfile_mailing_country_$TODAY  ON public.voterfile_new USING btree (mailing_country) ;"
	psql -c "CREATE INDEX voterfile_mailing_postal_code_$TODAY  ON public.voterfile_new USING btree (mailing_postal_code) ;"
	psql -c "CREATE INDEX voterfile_mailing_secondary_address_$TODAY  ON public.voterfile_new USING btree (mailing_secondary_address) ;"
	psql -c "CREATE INDEX voterfile_mailing_state_$TODAY  ON public.voterfile_new USING btree (mailing_state) ;"
	psql -c "CREATE INDEX voterfile_mailing_zip_$TODAY  ON public.voterfile_new USING btree (mailing_zip) ;"
	psql -c "CREATE INDEX voterfile_mailing_zip_plus4_$TODAY  ON public.voterfile_new USING btree (mailing_zip_plus4) ;"
	psql -c "CREATE INDEX voterfile_middle_name_$TODAY  ON public.voterfile_new USING btree (middle_name) ;"
	psql -c "CREATE INDEX voterfile_municipal_court_district_$TODAY  ON public.voterfile_new USING btree (municipal_court_district) ;"
	psql -c "CREATE INDEX voterfile_party_affiliation_$TODAY  ON public.voterfile_new USING btree (party_affiliation) ;"
	psql -c "CREATE INDEX voterfile_precinct_code_$TODAY  ON public.voterfile_new USING btree (precinct_code) ;"
	psql -c "CREATE INDEX voterfile_precinct_name_$TODAY  ON public.voterfile_new USING btree (precinct_name) ;"
	psql -c "CREATE INDEX voterfile_primary_03_02_2004_$TODAY  ON public.voterfile_new USING btree (primary_03_02_2004) ;"
	psql -c "CREATE INDEX voterfile_primary_03_04_2008_$TODAY  ON public.voterfile_new USING btree (primary_03_04_2008) ;"
	psql -c "CREATE INDEX voterfile_primary_03_06_2012_$TODAY  ON public.voterfile_new USING btree (primary_03_06_2012) ;"
	psql -c "CREATE INDEX voterfile_primary_03_07_2000_$TODAY  ON public.voterfile_new USING btree (primary_03_07_2000) ;"
	psql -c "CREATE INDEX voterfile_primary_03_15_2016_$TODAY  ON public.voterfile_new USING btree (primary_03_15_2016) ;"
	psql -c "CREATE INDEX voterfile_primary_05_02_2006_$TODAY  ON public.voterfile_new USING btree (primary_05_02_2006) ;"
	psql -c "CREATE INDEX voterfile_primary_05_02_2017_$TODAY  ON public.voterfile_new USING btree (primary_05_02_2017) ;"
	psql -c "CREATE INDEX voterfile_primary_05_03_2005_$TODAY  ON public.voterfile_new USING btree (primary_05_03_2005) ;"
	psql -c "CREATE INDEX voterfile_primary_05_03_2011_$TODAY  ON public.voterfile_new USING btree (primary_05_03_2011) ;"
	psql -c "CREATE INDEX voterfile_primary_05_04_2010_$TODAY  ON public.voterfile_new USING btree (primary_05_04_2010) ;"
	psql -c "CREATE INDEX voterfile_primary_05_05_2009_$TODAY  ON public.voterfile_new USING btree (primary_05_05_2009) ;"
	psql -c "CREATE INDEX voterfile_primary_05_05_2015_$TODAY  ON public.voterfile_new USING btree (primary_05_05_2015) ;"
	psql -c "CREATE INDEX voterfile_primary_05_06_2014_$TODAY  ON public.voterfile_new USING btree (primary_05_06_2014) ;"
	psql -c "CREATE INDEX voterfile_primary_05_07_2002_$TODAY  ON public.voterfile_new USING btree (primary_05_07_2002) ;"
	psql -c "CREATE INDEX voterfile_primary_05_07_2013_$TODAY  ON public.voterfile_new USING btree (primary_05_07_2013) ;"
	psql -c "CREATE INDEX voterfile_primary_05_08_2007_$TODAY  ON public.voterfile_new USING btree (primary_05_08_2007) ;"
	psql -c "CREATE INDEX voterfile_primary_05_08_2018_$TODAY  ON public.voterfile_new USING btree (primary_05_08_2018) ;"
	psql -c "CREATE INDEX voterfile_primary_07_13_2010_$TODAY  ON public.voterfile_new USING btree (primary_07_13_2010) ;"
	psql -c "CREATE INDEX voterfile_primary_09_07_2010_$TODAY  ON public.voterfile_new USING btree (primary_09_07_2010) ;"
	psql -c "CREATE INDEX voterfile_primary_09_08_2009_$TODAY  ON public.voterfile_new USING btree (primary_09_08_2009) ;"
	psql -c "CREATE INDEX voterfile_primary_09_10_2013_$TODAY  ON public.voterfile_new USING btree (primary_09_10_2013) ;"
	psql -c "CREATE INDEX voterfile_primary_09_11_2007_$TODAY  ON public.voterfile_new USING btree (primary_09_11_2007) ;"
	psql -c "CREATE INDEX voterfile_primary_09_12_2017_$TODAY  ON public.voterfile_new USING btree (primary_09_12_2017) ;"
	psql -c "CREATE INDEX voterfile_primary_09_13_2005_$TODAY  ON public.voterfile_new USING btree (primary_09_13_2005) ;"
	psql -c "CREATE INDEX voterfile_primary_09_13_2011_$TODAY  ON public.voterfile_new USING btree (primary_09_13_2011) ;"
	psql -c "CREATE INDEX voterfile_primary_09_13_2016_$TODAY  ON public.voterfile_new USING btree (primary_09_13_2016) ;"
	psql -c "CREATE INDEX voterfile_primary_09_15_2009_$TODAY  ON public.voterfile_new USING btree (primary_09_15_2009) ;"
	psql -c "CREATE INDEX voterfile_primary_09_15_2015_$TODAY  ON public.voterfile_new USING btree (primary_09_15_2015) ;"
	psql -c "CREATE INDEX voterfile_primary_09_29_2009_$TODAY  ON public.voterfile_new USING btree (primary_09_29_2009) ;"
	psql -c "CREATE INDEX voterfile_primary_10_01_2013_$TODAY  ON public.voterfile_new USING btree (primary_10_01_2013) ;"
	psql -c "CREATE INDEX voterfile_primary_10_14_2008_$TODAY  ON public.voterfile_new USING btree (primary_10_14_2008) ;"
	psql -c "CREATE INDEX voterfile_primary_11_06_2007_$TODAY  ON public.voterfile_new USING btree (primary_11_06_2007) ;"
	psql -c "CREATE INDEX voterfile_registration_date_$TODAY  ON public.voterfile_new USING btree (registration_date) ;"
	psql -c "CREATE INDEX voterfile_residential_address1_$TODAY  ON public.voterfile_new USING btree (residential_address1) ;"
	psql -c "CREATE INDEX voterfile_residential_city_$TODAY  ON public.voterfile_new USING btree (residential_city) ;"
	psql -c "CREATE INDEX voterfile_residential_country_$TODAY  ON public.voterfile_new USING btree (residential_country) ;"
	psql -c "CREATE INDEX voterfile_residential_postalcode_$TODAY  ON public.voterfile_new USING btree (residential_postalcode) ;"
	psql -c "CREATE INDEX voterfile_residential_secondary_addr_$TODAY  ON public.voterfile_new USING btree (residential_secondary_addr) ;"
	psql -c "CREATE INDEX voterfile_residential_state_$TODAY  ON public.voterfile_new USING btree (residential_state) ;"
	psql -c "CREATE INDEX voterfile_residential_zip_$TODAY  ON public.voterfile_new USING btree (residential_zip) ;"
	psql -c "CREATE INDEX voterfile_residential_zip_plus4_$TODAY  ON public.voterfile_new USING btree (residential_zip_plus4) ;"
	psql -c "CREATE INDEX voterfile_special_02_07_2006_$TODAY  ON public.voterfile_new USING btree (special_02_07_2006) ;"
	psql -c "CREATE INDEX voterfile_special_02_08_2005_$TODAY  ON public.voterfile_new USING btree (special_02_08_2005) ;"
	psql -c "CREATE INDEX voterfile_special_05_06_2003_$TODAY  ON public.voterfile_new USING btree (special_05_06_2003) ;"
	psql -c "CREATE INDEX voterfile_special_05_08_2001_$TODAY  ON public.voterfile_new USING btree (special_05_08_2001) ;"
	psql -c "CREATE INDEX voterfile_state_board_of_education_$TODAY  ON public.voterfile_new USING btree (state_board_of_education) ;"
	psql -c "CREATE INDEX voterfile_state_representative_district_$TODAY  ON public.voterfile_new USING btree (state_representative_district) ;"
	psql -c "CREATE INDEX voterfile_state_senate_district_$TODAY  ON public.voterfile_new USING btree (state_senate_district) ;"
	psql -c "CREATE INDEX voterfile_suffix_$TODAY  ON public.voterfile_new USING btree (suffix) ;"
	psql -c "CREATE INDEX voterfile_township_$TODAY  ON public.voterfile_new USING btree (township) ;"
	psql -c "CREATE INDEX voterfile_village_$TODAY  ON public.voterfile_new USING btree (village) ;"
	psql -c "CREATE INDEX voterfile_voter_status_$TODAY  ON public.voterfile_new USING btree (voter_status) ;"
	psql -c "CREATE INDEX voterfile_ward_$TODAY  ON public.voterfile_new USING btree (ward) ;"
fi

psql -f vv_create.sql

psql -c "CREATE INDEX gin_metaphone_all_last_new_idx_$TODAY ON public.vote_verify_new USING gin (((county)::text), metaphone((first_name)::text, 4), metaphone((last_name)::text, 8) gin_trgm_ops);"
psql -c "CREATE INDEX btree_upper_concat_name_idx_$TODAY ON public.vote_verify_new USING btree (upper((((county)::text || (last_name)::text) || (first_name)::text)));"
psql -c "CREATE INDEX btree_middle_name_idx_$TODAY ON public.vote_verify_new USING btree (middle_name);"
psql -c "CREATE INDEX birth_year_idx_$TODAY on public.vote_verify_new  USING btree (birth_year);"
psql -c "grant select on table public.vote_verify_new to ohiovotes;"

tail -n20 logs/log_$TODAY.txt | sendEmail -f adam@ohvoice.org -t adam@ohvoice.org -u "Voter File Updated - Check and Commit" -s "$MAILSERVER" -o tls=yes -xu "$MAIL" -xp "$PASS"
